urlDownloader.pages=1
urlDownloader.pageSize=10
urlDownloader.sort=activity
urlDownloader.order=desc
urlDownloader.path=./data/url-downloads
urlDownloader.maxParallel=4
urlDownloader.stackExchangeBaseUrl=https://api.stackexchange.com/2.3
urlDownloader.requestTimeoutSeconds=20
urlDownloader.serverHost=0.0.0.0
urlDownloader.serverPort=8082
